#!/usr/bin/env bash
# One-shot setup after copying ultralytics to a new machine.
# - Writes dataset yaml paths for this host
# - Creates datasets/llvip_{rgb,ir} symlinks to LLVIP
#
# Usage:
#   cp tools/machine.env.example tools/machine.env   # edit WORKSPACE
#   bash tools/setup_new_machine.sh
#
# Or:
#   WORKSPACE=/path/to/workspace bash tools/setup_new_machine.sh

set -euo pipefail

ULTRA_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ULTRA_ROOT/tools/machine.env"

if [[ -f "$ENV_FILE" ]]; then
  # shellcheck source=/dev/null
  source "$ENV_FILE"
fi

WORKSPACE="${WORKSPACE:-$(dirname "$ULTRA_ROOT")}"
WORKSPACE="$(cd "$WORKSPACE" && pwd)"

resolve_llvip_root() {
  if [[ -n "${LLVIP_ROOT:-}" ]]; then
    echo "$LLVIP_ROOT"
    return
  fi
  if [[ -d "$WORKSPACE/LLVIP/visible/train" ]]; then
    echo "$WORKSPACE/LLVIP"
    return
  fi
  if [[ -d "$WORKSPACE/multispectral-object-detection/LLVIP/visible/train" ]]; then
    echo "$WORKSPACE/multispectral-object-detection/LLVIP"
    return
  fi
  echo ""
}

LLVIP="$(resolve_llvip_root)"
if [[ -z "$LLVIP" ]]; then
  cat << EOF
ERROR: LLVIP not found.

Place the dataset at one of:
  $WORKSPACE/LLVIP/
  $WORKSPACE/multispectral-object-detection/LLVIP/

Expected layout (labels as .txt beside .jpg):
  LLVIP/visible/train/
  LLVIP/visible/test/
  LLVIP/infrared/train/
  LLVIP/infrared/test/

Download: https://github.com/bupt-ai-cz/LLVIP/blob/main/download_dataset.md
If you only have VOC xml, run voc_to_yolo (see cft_yolov8_config.md section 12).

Then re-run: bash tools/setup_new_machine.sh
EOF
  exit 1
fi

CFG_DIR="$ULTRA_ROOT/ultralytics/cfg/datasets"
mkdir -p "$CFG_DIR" "$ULTRA_ROOT/datasets"

write_yaml() {
  local file=$1
  cat > "$file"
  echo "  wrote $file"
}

write_yaml "$CFG_DIR/llvip_rgb.yaml" << EOF
# LLVIP visible (RGB) — auto-generated by tools/setup_new_machine.sh
path: $ULTRA_ROOT/datasets/llvip_rgb
train: images/train
val: images/test

nc: 1
names:
  0: person
EOF

write_yaml "$CFG_DIR/llvip_ir.yaml" << EOF
# LLVIP infrared — auto-generated by tools/setup_new_machine.sh
path: $ULTRA_ROOT/datasets/llvip_ir
train: images/train
val: images/test

nc: 1
names:
  0: person
EOF

write_yaml "$CFG_DIR/llvip_dual.yaml" << EOF
# LLVIP dual RGB+IR — auto-generated by tools/setup_new_machine.sh
path: $LLVIP
train_rgb: visible/train
val_rgb: visible/test
train_ir: infrared/train
val_ir: infrared/test

nc: 1
names:
  0: person
EOF

export LLVIP_ROOT="$LLVIP"
bash "$ULTRA_ROOT/tools/setup_llvip_symlinks.sh"

count_jpg() {
  find "$1" -maxdepth 1 -name '*.jpg' 2> /dev/null | wc -l
}

echo ""
echo "=== Setup OK ==="
echo "WORKSPACE:  $WORKSPACE"
echo "ULTRA_ROOT: $ULTRA_ROOT"
echo "LLVIP:      $LLVIP"
echo ""
echo "Image counts (expect train ~12025, test ~3463 per modality):"
for split in visible/train visible/test infrared/train infrared/test; do
  n=$(count_jpg "$LLVIP/$split")
  echo "  $split: $n"
done
echo ""
echo "Next:"
echo "  cd $ULTRA_ROOT"
echo "  pip install -e ."
echo "  yolo train model=yolov8l.pt data=ultralytics/cfg/datasets/llvip_rgb.yaml ..."
