#!/usr/bin/env bash
# Configure VEDAI paths for YOLOv8+CFT dual-stream training.
#
# Usage:
#   cp tools/machine.env.example tools/machine.env   # set WORKSPACE / VEDAI_ROOT
#   bash tools/setup_vedai.sh
#
# Expected layout (after YOLO-format conversion):
#   <VEDAI_ROOT>/Vehicules1024/Images/color/fold01.txt
#   <VEDAI_ROOT>/Vehicules1024/Images/color/fold01test.txt
#   <VEDAI_ROOT>/Vehicules1024/Images/ir/fold01.txt
#   <VEDAI_ROOT>/Vehicules1024/Images/ir/fold01test.txt
#   plus paired *_co.png / *_ir.png and same-stem .txt labels beside color images.

set -euo pipefail

ULTRA_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ULTRA_ROOT/tools/machine.env"
[[ -f "$ENV_FILE" ]] && source "$ENV_FILE"

WORKSPACE="${WORKSPACE:-$(dirname "$ULTRA_ROOT")}"
WORKSPACE="$(cd "$WORKSPACE" && pwd)"

resolve_vedai_root() {
  if [[ -n "${VEDAI_ROOT:-}" ]]; then
    echo "$VEDAI_ROOT"
    return
  fi
  for d in "$WORKSPACE/VEDAI" "$WORKSPACE/vedai" "$WORKSPACE/multispectral-object-detection/VEDAI"; do
    if [[ -f "$d/Vehicules1024/Images/color/fold01.txt" ]]; then
      echo "$d"
      return
    fi
  done
  echo ""
}

VEDAI="$(resolve_vedai_root)"
VEH="$VEDAI/Vehicules1024"
if [[ -z "$VEDAI" || ! -f "$VEH/Images/color/fold01.txt" ]]; then
  cat << EOF
ERROR: VEDAI not found.

Download from https://downloads.greyc.fr/vedai/ and convert annotations to YOLO format.
Place data at:
  $WORKSPACE/VEDAI/Vehicules1024/Images/{color,ir}/

Required list files:
  Images/color/fold01.txt, fold01test.txt
  Images/ir/fold01.txt, fold01test.txt

See cft_yolov8_config.md section 十四 (VEDAI) for preparation steps.
Then set VEDAI_ROOT in tools/machine.env and re-run: bash tools/setup_vedai.sh
EOF
  exit 1
fi

CFG="$ULTRA_ROOT/ultralytics/cfg/datasets/vedai_dual.yaml"
cat > "$CFG" << EOF
# VEDAI dual RGB+IR — auto-generated by tools/setup_vedai.sh
path: $VEH
train_rgb: Images/color/fold01.txt
val_rgb: Images/color/fold01test.txt
train_ir: Images/ir/fold01.txt
val_ir: Images/ir/fold01test.txt

nc: 9
names:
  0: car
  1: truck
  2: pickup
  3: tractor
  4: camping car
  5: boat
  6: plane
  7: van
  8: other
EOF

count_lines() { wc -l < "$1" | tr -d ' '; }

echo "=== VEDAI setup OK ==="
echo "VEDAI_ROOT: $VEDAI"
echo "Wrote:      $CFG"
echo ""
echo "List counts (expect 128 train + 128 val per modality):"
for f in Images/color/fold01.txt Images/color/fold01test.txt Images/ir/fold01.txt Images/ir/fold01test.txt; do
  echo "  $f: $(count_lines "$VEH/$f")"
done
echo ""
echo "Train Y8-CFT on VEDAI:"
echo "  python tools/train_cft.py \\"
echo "    model=ultralytics/cfg/models/v8/yolov8s_fusion_transformerx3_vedai.yaml \\"
echo "    data=ultralytics/cfg/datasets/vedai_dual.yaml \\"
echo "    pretrained=yolov8s.pt epochs=100 imgsz=1024 batch=4 nbs=16 workers=4 device=0 \\"
echo "    project=runs/vedai name=y8_cft exist_ok=True"
